#!/usr/bin/env bash
# Regenerate the [theme.custom] block in config.toml from omarchy's current theme.
#
# herdr only ships `catppuccin` (Mocha) and `catppuccin-latte`, so the palette
# lives in config.toml as explicit token overrides. That block is pinned to
# Catppuccin Frappe, which drifts as soon as `omarchy-theme-set` picks something
# else. Run this after a theme switch to bring herdr back in line.
#
# omarchy's colors.toml exposes an accent, a fg/bg pair and the 16 ANSI colours.
# Named hues map across directly. herdr's structural tokens (panel_bg,
# surface_dim, surface0, overlay0/1) have no source entry, so they are derived
# by shading the background toward black or the foreground. On Frappe those
# derivations land within a couple of hex digits of the real Catppuccin values,
# but they are approximations, not the published palette.
set -euo pipefail

CONFIG="${HERDR_CONFIG_PATH:-${XDG_CONFIG_HOME:-$HOME/.config}/herdr/config.toml}"
THEME_DIR="${OMARCHY_THEME_DIR:-$HOME/.config/omarchy/current/theme}"
COLORS="$THEME_DIR/colors.toml"

[[ -r "$COLORS" ]] || { echo "no omarchy colors.toml at $COLORS" >&2; exit 1; }
[[ -r "$CONFIG" ]] || { echo "no herdr config at $CONFIG" >&2; exit 1; }

# Read `key = "#rrggbb"` out of colors.toml.
get() {
  local v
  v=$(sed -nE "s/^$1[[:space:]]*=[[:space:]]*\"(#[0-9a-fA-F]{6})\".*/\1/p" "$COLORS" | head -1)
  [[ -n "$v" ]] || { echo "colors.toml is missing '$1'" >&2; exit 1; }
  printf '%s' "$v"
}

# mix <hex-a> <hex-b> <weight>  ->  a blended toward b by weight (0..1)
mix() {
  local a=${1#\#} b=${2#\#} w=$3
  printf '#%02x%02x%02x' \
    "$(( (0x${a:0:2} * (1000 - ${w})) / 1000 + (0x${b:0:2} * ${w}) / 1000 ))" \
    "$(( (0x${a:2:2} * (1000 - ${w})) / 1000 + (0x${b:2:2} * ${w}) / 1000 ))" \
    "$(( (0x${a:4:2} * (1000 - ${w})) / 1000 + (0x${b:4:2} * ${w}) / 1000 ))"
}

bg=$(get background); fg=$(get foreground); accent=$(get accent)
c0=$(get color0);  c1=$(get color1);  c2=$(get color2);  c3=$(get color3)
c4=$(get color4);  c5=$(get color5);  c6=$(get color6);  c15=$(get color15)
black="#000000"

block=$(cat <<EOF
[theme.custom]
# Generated by scripts/sync-omarchy-theme.sh from $THEME_DIR/colors.toml
# Structural tokens are derived by shading; hues come straight from the theme.
panel_bg = "$(mix "$bg" "$black" 120)"
surface_dim = "$(mix "$bg" "$black" 250)"
surface0 = "$(mix "$bg" "$fg" 100)"
surface1 = "$c0"
overlay0 = "$(mix "$bg" "$fg" 420)"
overlay1 = "$(mix "$bg" "$fg" 520)"
text = "$fg"
subtext0 = "$c15"
accent = "$accent"
blue = "$c4"
teal = "$c6"
green = "$c2"
yellow = "$c3"
peach = "$(mix "$c1" "$c3" 500)"
red = "$c1"
mauve = "$c5"
EOF
)

grep -q '^# BEGIN THEME TOKENS$' "$CONFIG" || { echo "marker '# BEGIN THEME TOKENS' not found in $CONFIG" >&2; exit 1; }

tmp=$(mktemp)
awk -v block="$block" '
  /^# BEGIN THEME TOKENS$/ { print; print block; skip = 1; next }
  /^# END THEME TOKENS$/   { skip = 0 }
  !skip { print }
' "$CONFIG" > "$tmp"
mv "$tmp" "$CONFIG"

if HERDR_CONFIG_PATH="$CONFIG" herdr config check; then
  echo "synced [theme.custom] from $(cat "$THEME_DIR/../theme.name" 2>/dev/null || echo "$THEME_DIR")"
  herdr server reload-config 2>/dev/null || echo "(no running herdr server to reload)"
fi
